### ISSUE TITLE
Not and issue, just a request/question....

### ISSUE THREAD

**Issue by DustinWatts** [andrewfernie/FreeTouchDeckWT32#10]
Hi Andrew,

Dustin Watts here. I could not find another way to get in touch with you so I'll do it here. Do you mind if I link to this repository on the original FreeTouchDeck repo? I just got a message from a use who got his board working with your repo/fork, and as I like to have as many people as I can to use all sorts off boards I link to repo's/forks that work for different boards. 

If so, I would like to know what the exact serial number of the board is and I will link it here: https://github.com/DustinWatts/FreeTouchDeck?tab=readme-ov-file#community-support

Cheers,
Dustin Watts

**Comment by andrewfernie** [comment]
Sure, Dustin. Go ahead.

I am using the "WT32-SC01" board.  There is a related "WT32-SC01 Plus" which will not work as it is using a parallel interface to the LCD, not SPI.

Thank you for developing Freetouchdeck, it really is good. I took my fork and  added hardware buttons and a joystick to act as a joystick for CAD programs. It is in my "CADDeck" repo. The only difficulty I have is the configurator, which got less and less reliable as I added more parameters, and I have moved over to a PC based app that edits the json files. I can upload them on WiFi with a simplified configurator, or upload the full file system in the IDE. It also supports png logos, and as they are smaller than bmp I can store many more. The png library is heavy on RAM usage, but light on the CPU.
