### ISSUE TITLE
esp_littlefs: mount failed,  (-84)

### ISSUE THREAD

**Issue by intensecity** [andrewfernie/FreeTouchDeckWT32#11]
Hi Andrew,

I'm having some serious bad luck getting this project to run on my WT32-SC01 (basic). I have compiled it using VSCode 1.88.1 in Windows and uploaded successfully, but when running I'm met with the message "Failed to init LittleFS! Did you upload the data folder?" on the screen. I retried in a fresh Windows OS with just the recommended extensions (I even tried Ubuntu), but am met with the same result.

I've attached the console logs:
[upload.txt](https://github.com/andrewfernie/FreeTouchDeckWT32/files/14956509/upload.txt)
[monitor.txt](https://github.com/andrewfernie/FreeTouchDeckWT32/files/14956508/monitor.txt)

Any ideas what I can do to resolve this issue?

Thank you!

**Comment by andrewfernie** [comment]
Have you  uploaded the file system - it contains all of the icons and json configuration files. You do this by selecting the "Upload Filesystem Image" item in the PlatformIO Project Tasks in VS Code. 

![image](https://github.com/andrewfernie/FreeTouchDeckWT32/assets/3051808/18bf692e-75e7-4850-ac32-98afcbe1a868)

**Comment by intensecity** [comment]
That'll do it!

Sorry, I'm new to PlatformIO. I haven't found any good guides for FreeTouchDeck/WT32 for people who don't already know what they're doing, so this has been a good learning journey.

Appreciate the support!

**Comment by andrewfernie** [comment]
I am happy to hear that it worked OK.
